version: '3.8'

services:
  db:
    image: postgres:14
    container_name: cms_postgres_db
    environment:
      POSTGRES_USER: cms_user
      POSTGRES_PASSWORD: cms_password
      POSTGRES_DB: cms_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  nextjs:
    build:
      context: . # This points to the Dockerfile location
      dockerfile: Dockerfile
    container_name: cms_nextjs_app
    environment:
      DATABASE_URL: "postgresql://cms_user:cms_password@db:5432/cms_db"
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/app           # Mount the current directory to /app in the container
      - /app/node_modules # Avoid mounting node_modules for stability

volumes:
  pgdata: {}
